### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by GameWatch21**

### CODE REVIEW

**Comment by GameWatch21** [comment]
faking typo

**Comment by NekoIceCream** [comment]
Seriousy?

**Comment by GameWatch21** [comment]
WTF

**Comment by NekoIceCream** [comment]
Dont close

**Comment by NekoIceCream** [comment]
Wait ok

**Comment by GameWatch21** [comment]
ok

**Comment by NekoIceCream** [comment]
Done

**Comment by GameWatch21** [comment]
good lmao

**Pull request merged**
