### PR TITLE
Add Music Bot And MongoDB (Patch_2)

### PR DESCRIPTION
**Pull request by NekoIceCream**

### CODE REVIEW

**Comment by NekoIceCream** [comment]
Maybe add blacklist and add mongodb :l

**Comment by GameWatch21** [comment]
imagine using mongodb

**Comment by NekoIceCream** [comment]
Lmao maybe i need modified index.js and add mongodb

**Comment by GameWatch21** [comment]
you need to create db.js with mongodb user, password inside

**Comment by NekoIceCream** [comment]
Hm

**Comment by NekoIceCream** [comment]
I forget about package-lock

**Comment by NekoIceCream** [comment]
> you need to create db.js with mongodb user, password inside

Yeah i know. I've used mongodb

**Comment by NekoIceCream** [comment]
Bruh missing file

Canceled merge

**Comment by NekoIceCream** [comment]
Missing again 🗿

**Comment by NekoIceCream** [comment]
Bruh

**Comment by NekoIceCream** [comment]
Mongodb done maybe

now Just a music bot

**Comment by GameWatch21** [comment]
Music bot huh

**Comment by NekoIceCream** [comment]
Bruh

**Pull request closed without merging**
