### PR TITLE
Embed update

### PR DESCRIPTION
**Pull request by GameWatch21**

### CODE REVIEW

**Comment by NekoIceCream** [comment]
Commitnya membagongkan

**Comment by GameWatch21** [comment]
Done _maybe_

**Comment by NekoIceCream** [comment]
`Yowes`

**Comment by NekoIceCream** [comment]
Asal ga outdated

**Comment by GameWatch21** [comment]
You erase the footer and the embed is outdated

**Comment by GameWatch21** [comment]
pakai indo aja lebih enak :v

**Pull request merged**
